[2025-03-09T17:50:32.100+0000] {processor.py:186} INFO - Started process (PID=722) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:50:32.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:50:32.103+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:50:32.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:50:32.115+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:50:32.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:50:32.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:50:32.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.040 seconds
[2025-03-09T17:51:02.850+0000] {processor.py:186} INFO - Started process (PID=787) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:02.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:51:02.854+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:51:02.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:02.868+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:51:02.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:51:02.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:02.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.047 seconds
[2025-03-09T17:51:33.025+0000] {processor.py:186} INFO - Started process (PID=853) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:33.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:51:33.028+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:51:33.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:33.039+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:51:33.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:51:33.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:51:33.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.041 seconds
[2025-03-09T17:52:03.345+0000] {processor.py:186} INFO - Started process (PID=919) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:03.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:52:03.351+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:52:03.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:03.369+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:52:03.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:52:03.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:03.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.057 seconds
[2025-03-09T17:52:34.036+0000] {processor.py:186} INFO - Started process (PID=985) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:34.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:52:34.039+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:52:34.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:34.054+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:52:34.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:52:34.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:52:34.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.048 seconds
[2025-03-09T17:53:04.281+0000] {processor.py:186} INFO - Started process (PID=1051) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:04.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:53:04.285+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:53:04.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:04.296+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:53:04.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:53:04.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:04.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.042 seconds
[2025-03-09T17:53:34.978+0000] {processor.py:186} INFO - Started process (PID=1117) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:34.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:53:34.983+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:53:34.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:34.995+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:53:34.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:53:34.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:53:35.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.045 seconds
[2025-03-09T17:54:06.135+0000] {processor.py:186} INFO - Started process (PID=1182) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:06.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:54:06.143+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:54:06.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:06.162+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:54:06.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:54:06.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:06.201+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.074 seconds
[2025-03-09T17:54:36.656+0000] {processor.py:186} INFO - Started process (PID=1247) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:36.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:54:36.660+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:54:36.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:36.674+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:54:36.673+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:54:36.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:54:36.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.045 seconds
[2025-03-09T17:55:07.375+0000] {processor.py:186} INFO - Started process (PID=1307) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:07.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:55:07.378+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:55:07.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:07.391+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:55:07.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:55:07.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:07.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.056 seconds
[2025-03-09T17:55:37.508+0000] {processor.py:186} INFO - Started process (PID=1372) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:37.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:55:37.512+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:55:37.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:37.527+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:55:37.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:55:37.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:55:37.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.049 seconds
[2025-03-09T17:56:09.138+0000] {processor.py:186} INFO - Started process (PID=1426) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:09.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:56:09.143+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:56:09.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:09.158+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:56:09.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:56:09.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:09.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.055 seconds
[2025-03-09T17:56:40.620+0000] {processor.py:186} INFO - Started process (PID=1488) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:40.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:56:40.624+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:56:40.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:40.635+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:56:40.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:56:40.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:56:40.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.046 seconds
[2025-03-09T17:57:10.781+0000] {processor.py:186} INFO - Started process (PID=1553) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:10.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:57:10.786+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:10.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:10.803+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:10.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:57:10.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:10.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.077 seconds
[2025-03-09T17:57:41.700+0000] {processor.py:186} INFO - Started process (PID=1614) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:41.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:57:41.705+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:41.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:41.720+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:41.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 25
    mail_folder_id="AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYw
                   ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-03-09T17:57:41.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:41.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.048 seconds
[2025-03-09T17:57:52.683+0000] {processor.py:186} INFO - Started process (PID=1646) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:57:52.687+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.719+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:57:52.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.069 seconds
[2025-03-09T17:57:52.794+0000] {processor.py:186} INFO - Started process (PID=1647) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:57:52.798+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.827+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:57:52.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.067 seconds
[2025-03-09T17:57:52.909+0000] {processor.py:186} INFO - Started process (PID=1648) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:57:52.915+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.941+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:57:52.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:57:52.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:57:52.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.062 seconds
[2025-03-09T17:58:23.028+0000] {processor.py:186} INFO - Started process (PID=1714) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:23.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:58:23.031+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:58:23.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:23.053+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:58:23.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:58:23.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:23.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.051 seconds
[2025-03-09T17:58:53.812+0000] {processor.py:186} INFO - Started process (PID=1780) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:53.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:58:53.817+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:58:53.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:53.889+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:58:53.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:58:53.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:58:53.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.122 seconds
[2025-03-09T17:59:24.249+0000] {processor.py:186} INFO - Started process (PID=1846) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:24.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:59:24.253+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:59:24.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:24.281+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:59:24.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:59:24.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:24.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.066 seconds
[2025-03-09T17:59:54.877+0000] {processor.py:186} INFO - Started process (PID=1912) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:54.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T17:59:54.881+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:59:54.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:54.921+0000] {logging_mixin.py:190} INFO - [2025-03-09T17:59:54.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T17:59:54.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T17:59:54.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.091 seconds
[2025-03-09T18:00:25.117+0000] {processor.py:186} INFO - Started process (PID=1978) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:25.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:00:25.121+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:00:25.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:25.146+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:00:25.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T18:00:25.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:25.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.057 seconds
[2025-03-09T18:00:55.690+0000] {processor.py:186} INFO - Started process (PID=2035) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:55.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:00:55.701+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:00:55.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:55.751+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:00:55.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T18:00:55.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:00:55.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.125 seconds
[2025-03-09T18:01:26.011+0000] {processor.py:186} INFO - Started process (PID=2101) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:26.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:01:26.017+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:01:26.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:26.044+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:01:26.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T18:01:26.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:26.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.065 seconds
[2025-03-09T18:01:56.379+0000] {processor.py:186} INFO - Started process (PID=2160) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:56.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:01:56.382+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:01:56.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:56.426+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:01:56.413+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 17
    'AAMkADYxM2NlOTI5LWY1MTktNGMyNy1hNjY1LWJhYWJiNWZiZTgyYwAuAAAAAAC5
    ^
SyntaxError: unterminated string literal (detected at line 17)
[2025-03-09T18:01:56.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:01:56.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.098 seconds
[2025-03-09T18:02:26.522+0000] {processor.py:186} INFO - Started process (PID=2226) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:26.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:02:26.526+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:02:26.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:26.549+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:02:26.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 10
    super().__init__(*args, **kwargs)
    ^^^^^
IndentationError: expected an indented block after function definition on line 8
[2025-03-09T18:02:26.550+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:26.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.054 seconds
[2025-03-09T18:02:57.051+0000] {processor.py:186} INFO - Started process (PID=2284) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:57.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:02:57.054+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:02:57.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:57.075+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:02:57.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 10
    super().__init__(*args, **kwargs)
    ^^^^^
IndentationError: expected an indented block after function definition on line 8
[2025-03-09T18:02:57.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:02:57.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.050 seconds
[2025-03-09T18:03:27.916+0000] {processor.py:186} INFO - Started process (PID=2347) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:27.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:03:27.920+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:03:27.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:27.948+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:03:27.944+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 10
    super().__init__(*args, **kwargs)
    ^^^^^
IndentationError: expected an indented block after function definition on line 8
[2025-03-09T18:03:27.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:27.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.061 seconds
[2025-03-09T18:03:58.250+0000] {processor.py:186} INFO - Started process (PID=2401) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:58.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:03:58.254+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:03:58.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:58.279+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:03:58.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/extraiEmail.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/extraiEmail.py", line 3, in <module>
    from extrai_email_operator import ExtraiEmailOperator
  File "/opt/airflow/plugins/extrai_email_operator.py", line 10
    super().__init__(*args, **kwargs)
    ^^^^^
IndentationError: expected an indented block after function definition on line 8
[2025-03-09T18:03:58.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:03:58.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.059 seconds
[2025-03-09T18:04:28.498+0000] {processor.py:186} INFO - Started process (PID=2462) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:28.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:04:28.504+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:28.543+0000] {processor.py:925} INFO - DAG(s) 'extract_outlook_attachments' retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:28.666+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.665+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:extract_outlook_attachments
[2025-03-09T18:04:28.680+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.680+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:extract_outlook_attachments
[2025-03-09T18:04:28.692+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.692+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:extract_outlook_attachments
[2025-03-09T18:04:28.707+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.707+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:extract_outlook_attachments
[2025-03-09T18:04:28.716+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.716+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:extract_outlook_attachments
[2025-03-09T18:04:28.730+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.730+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:extract_outlook_attachments
[2025-03-09T18:04:28.743+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.742+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:extract_outlook_attachments
[2025-03-09T18:04:28.743+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.743+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-09T18:04:28.759+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.759+0000] {dag.py:3262} INFO - Creating ORM DAG for extract_outlook_attachments
[2025-03-09T18:04:28.772+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:28.772+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_outlook_attachments to 2025-03-08 00:00:00+00:00, run_after=2025-03-09 00:00:00+00:00
[2025-03-09T18:04:28.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.312 seconds
[2025-03-09T18:04:53.872+0000] {processor.py:186} INFO - Started process (PID=2528) to work on /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:53.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/extraiEmail.py for tasks to queue
[2025-03-09T18:04:53.875+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:53.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:53.910+0000] {processor.py:925} INFO - DAG(s) 'extract_outlook_attachments' retrieved from /opt/airflow/dags/extraiEmail.py
[2025-03-09T18:04:53.925+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:53.925+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-09T18:04:53.951+0000] {logging_mixin.py:190} INFO - [2025-03-09T18:04:53.951+0000] {dag.py:4180} INFO - Setting next_dagrun for extract_outlook_attachments to 2025-03-08 00:00:00+00:00, run_after=2025-03-09 00:00:00+00:00
[2025-03-09T18:04:53.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/extraiEmail.py took 0.109 seconds
