[2025-03-13T00:00:24.983+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T00:00:25.014+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-12T00:00:00+00:00 [queued]>
[2025-03-13T00:00:25.032+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-12T00:00:00+00:00 [queued]>
[2025-03-13T00:00:25.035+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-13T00:00:25.217+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): concatenar_dataframes> on 2025-03-12 00:00:00+00:00
[2025-03-13T00:00:25.226+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=456) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T00:00:25.228+0000] {standard_task_runner.py:72} INFO - Started process 458 to run task
[2025-03-13T00:00:25.228+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'processar_emails_excel_operador', 'concatenar_dataframes', 'scheduled__2025-03-12T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/extraiEmail.py', '--cfg-path', '/tmp/tmpnbta06q8']
[2025-03-13T00:00:25.230+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask concatenar_dataframes
[2025-03-13T00:00:25.300+0000] {task_command.py:467} INFO - Running <TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-12T00:00:00+00:00 [running]> on host 4052a614e333
[2025-03-13T00:00:25.421+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processar_emails_excel_operador' AIRFLOW_CTX_TASK_ID='concatenar_dataframes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T00:00:00+00:00'
[2025-03-13T00:00:25.423+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T00:00:25.424+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T00:00:25.425+0000] {logging_mixin.py:190} INFO - Current task name:concatenar_dataframes state:running start_date:2025-03-13 00:00:25.016144+00:00
[2025-03-13T00:00:25.426+0000] {logging_mixin.py:190} INFO - Dag name:processar_emails_excel_operador and current dag run status:running
[2025-03-13T00:00:25.427+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-13T00:00:25.442+0000] {logging_mixin.py:190} INFO - Nenhum DataFrame encontrado para converter.
[2025-03-13T00:00:25.443+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-13T00:00:25.457+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-13T00:00:25.459+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=processar_emails_excel_operador, task_id=concatenar_dataframes, run_id=scheduled__2025-03-12T00:00:00+00:00, execution_date=20250312T000000, start_date=20250313T000025, end_date=20250313T000025
[2025-03-13T00:00:25.476+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-13T00:00:25.477+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-13T00:00:25.478+0000] {logging_mixin.py:190} INFO - Dag name:processar_emails_excel_operador queued_at:2025-03-13 00:00:00.468394+00:00
[2025-03-13T00:00:25.478+0000] {logging_mixin.py:190} INFO - Task hostname:4052a614e333 operator:PythonOperator
[2025-03-13T00:00:25.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T00:00:25.546+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T00:00:25.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
