[2025-03-12T23:31:39.315+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T23:31:39.350+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-12T23:31:39.377+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-10T00:00:00+00:00 [queued]>
[2025-03-12T23:31:39.383+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-12T23:31:39.777+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): concatenar_dataframes> on 2025-03-10 00:00:00+00:00
[2025-03-12T23:31:39.790+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T23:31:39.793+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-03-12T23:31:39.793+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'processar_emails_excel_operador', 'concatenar_dataframes', 'scheduled__2025-03-10T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/extraiEmail.py', '--cfg-path', '/tmp/tmp5hsxmlx1']
[2025-03-12T23:31:39.796+0000] {standard_task_runner.py:105} INFO - Job 161: Subtask concatenar_dataframes
[2025-03-12T23:31:39.870+0000] {task_command.py:467} INFO - Running <TaskInstance: processar_emails_excel_operador.concatenar_dataframes scheduled__2025-03-10T00:00:00+00:00 [running]> on host 4052a614e333
[2025-03-12T23:31:39.993+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processar_emails_excel_operador' AIRFLOW_CTX_TASK_ID='concatenar_dataframes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T00:00:00+00:00'
[2025-03-12T23:31:39.995+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T23:31:39.997+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T23:31:39.998+0000] {logging_mixin.py:190} INFO - Current task name:concatenar_dataframes state:running start_date:2025-03-12 23:31:39.351287+00:00
[2025-03-12T23:31:39.999+0000] {logging_mixin.py:190} INFO - Dag name:processar_emails_excel_operador and current dag run status:running
[2025-03-12T23:31:40.001+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-12T23:31:40.019+0000] {logging_mixin.py:190} INFO - Nenhum DataFrame encontrado para converter.
[2025-03-12T23:31:40.020+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T23:31:40.038+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-12T23:31:40.040+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=processar_emails_excel_operador, task_id=concatenar_dataframes, run_id=scheduled__2025-03-10T00:00:00+00:00, execution_date=20250310T000000, start_date=20250312T233139, end_date=20250312T233140
[2025-03-12T23:31:40.062+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T23:31:40.063+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T23:31:40.064+0000] {logging_mixin.py:190} INFO - Dag name:processar_emails_excel_operador queued_at:2025-03-12 23:31:00.782679+00:00
[2025-03-12T23:31:40.065+0000] {logging_mixin.py:190} INFO - Task hostname:4052a614e333 operator:PythonOperator
[2025-03-12T23:31:40.135+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T23:31:40.186+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T23:31:40.192+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
